Birthminder/Birthminder/Models/UserRoles/ManagerUserRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Birthminder.Models
{

    public class ManageUserRolesViewModel
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Selected { get; set; }
    }
}

Birthminder/Birthminder/Models/UserRoles/UserRolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Birthminder.Models
{

    public class UserRolesViewModel
    {
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }

        [Column(TypeName = "date")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }
        public int TeamId { get; set; }
        public IEnumerable<string> Roles { get; set; }
    }
}

Birthminder/Birthminder/Controllers/UserRolesController.cs
using Birthminder.Data;
using Birthminder.Models;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MimeKit;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Birthminder.Controllers
{
    public class UserRolesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        public UserRolesController(UserManager<User> userManager, RoleManager<AppRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (User user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.FullName = user.FullName;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]

        public IActionResult AccessDenied()
        {
            return View();
        }

        private async Task<List<string>> GetUserRoles(User user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
    }
}

Birthminder/Birthminder/Views/UserRoles/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        p {
            font-family: "Segoe UI";
            font-size: 3vw;
            margin-top: 10vh;
        }

        .line {
            position: relative;
            width: 45vw;
            height: 5px;
            background-color: orange;
            border-radius: 25px;
        }

        .under-section {
            position: absolute;
            text-align: center;
            font-size: 1.5vw;
            font-family: "Segoe UI";
            left: 10vw;
        }

        #home {
            text-decoration: underline;
        }

        #button {
            padding-left: 55px;
            padding-right: 55px;
            padding-top: 10px;
            padding-bottom: 10px;
            border: 3px solid orange;
            background-color: orange;
            color: white;
            text-align: center;
            display: block;
            margin: 0 auto;
            font-size: 2vw;
            font-weight: 600;
            border-radius: 15px;
        }

            #button:hover {
                background-color: white;
                color: orange;
            }

        .pic {
            width: 45vw;
            height: auto;
            position: absolute;
            top: 5vh;
            left: -7vw;
        }
    </style>
    <h1>Access Denied</h1>
    <hr />
</head>

<div>
    <h2>Please login or register if needed!</h2>
    </div>

Birthminder/Birthminder/Views/UserRoles/Index.cshtml
@model List<Birthminder.Models.UserRolesViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width" />
    <h1>User Roles</h1>
</head>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Full name</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.FullName</td>
                <td>@user.Email</td>
                <td>@string.Join(" , ", user.Roles.ToList())</td>
                <td>
                    <a class="btn btn-primary" asp-controller="UserRoles" asp-action="Manage" asp-route-userId="@user.UserId">Manage Roles</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Birthminder/Birthminder/Views/UserRoles/Manage.cshtml
@model List<ManageUserRolesViewModel>
@{
    ViewData["Title"] = "Manage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width" />
    </head>
    <form method="post">
        <div class="card">
            <div class="card-header">
                <h2>Manage user roles</h2>
                Change role for user:
            </div>
            <div class="card-body">
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="form-check m-1">
                        <input type="hidden" asp-for="@Model[i].RoleId" />
                        <input type="hidden" asp-for="@Model[i].RoleName" />
                        <input asp-for="@Model[i].Selected" class="form-check-input" />
                        <label class="form-check-label" asp-for="@Model[i].Selected">
                            @Model[i].RoleName
                        </label>
                    </div>
                }
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <input type="submit" value="Update" class="btn btn-primary"
                       style="width:auto" />
                <a asp-action="EditUser" asp-route-id="@ViewBag.userId"
                   class="btn btn-primary" style="width:auto">Cancel</a>
            </div>
        </div>
    </form>